services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URL=file:dist/db/db.sqlite
    restart: unless-stopped
    volumes:
      - db-data:/dist/db/db.sqlite

volumes:
  db-data:
